// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MPP_ChoiceEX","status":true,"description":"【ver.3.11】選択肢の機能拡張","parameters":{"maxPageRow":"6","Disabled Index":"none","=== Command ===":"","Plugin Commands":"{\"ChoicePos\":\"ChoicePos\",\"ChoiceVariableId\":\"ChoiceVariableId\",\"ChoiceRect\":\"ChoiceRect\",\"ChoiceUnderMessage\":\"ChoiceUnderMessage\"}","Event Comment":"{\"ChoiceHelp\":\"選択肢ヘルプ\"}"}},
{"name":"Torigoya_CommonMenu","status":true,"description":"メニューからコモンイベント呼び出しプラグイン (v.1.0.0)","parameters":{"base":"","baseItems":"[\"{\\\"name\\\":\\\"テレポート\\\",\\\"commonEvent\\\":\\\"1\\\",\\\"switchId\\\":\\\"0\\\",\\\"visibility\\\":\\\"true\\\",\\\"note\\\":\\\"\\\"}\"]"}}
];
